excluded: # paths to ignore during linting. Takes precedence over `included`.
  - DerivedData
  - ResearchKit
disabled_rules:
  - weak_delegate
  - file_length
  - function_body_length
  - type_body_length
  - blanket_disable_command
